Fix two build failures due to new gcc-10 warnings, such as uninitialized variables and duplicated definitions:
e.g. of failure:
/usr/bin/ld: CMakeFiles/gtk-window-decorator.dir/gwd-settings-xproperty-storage.c.o:./obj-x86_64-linux-gnu/gtk/window-decorator/./gtk/window-decorator/gtk-window-decorator.h:269: multiple definition of `window_type_frames'; CMakeFiles/gtk-window-decorator.dir/gtk-window-decorator.c.o:./obj-x86_64-linux-gnu/gtk/window-decorator/./gtk/window-decorator/gtk-window-decorator.h:269: first defined here
/usr/bin/ld: CMakeFiles/gtk-window-decorator.dir/gwd-theme.c.o:./obj-x86_64-linux-gnu/gtk/window-decorator/./gtk/window-decorator/gtk-window-decorator.h:269: multiple definition of `window_type_frames'; CMakeFiles/gtk-window-decorator.dir/gtk-window-decorator.c.o:./obj-x86_64-linux-gnu/gtk/window-decorator/./gtk/window-decorator/gtk-window-decorator.h:269: first defined here
/usr/bin/ld: CMakeFiles/gtk-window-decorator.dir/gwd-theme-cairo.c.o:./obj-x86_64-linux-gnu/gtk/window-decorator/./gtk/window-decorator/gtk-window-decorator.h:269: multiple definition of `window_type_frames'; CMakeFiles/gtk-window-decorator.dir/gtk-window-decorator.c.o:./obj-x86_64-linux-gnu/gtk/window-decorator/./gtk/window-decorator/gtk-window-decorator.h:269: first defined here
/usr/bin/ld: CMakeFiles/gtk-window-decorator.dir/gwd-theme-metacity.c.o:./obj-x86_64-linux-gnu/gtk/window-decorator/./gtk/window-decorator/gtk-window-decorator.h:269: multiple definition of `window_type_frames'; CMakeFiles/gtk-window-decorator.dir/gtk-window-decorator.c.o:./obj-x86_64-linux-gnu/gtk/window-decorator/./gtk/window-decorator/gtk-window-decorator.h:269: first defined here
collect2: error: ld returned 1 exit status